### ISSUE TITLE
Fish In A Bucket quest causing permanent disconnection

### ISSUE THREAD

**Issue by arm358** [WowLegacyCore/HermesProxy#111]
**Describe the bug**
Gathered 5 Shellfish for the "Fish In A Bucket" quest in Shadowprey Village. As soon as I clicked "Complete" I was booted from the server with error WOW51900319.

I am no longer able to log into that character at all, but can log into other characters.

Hermes provides the following output error:
```
14:18:42 |  Error   | /home/runner/work/DarkHermesPatches/DarkHermesPatches/HermesProxy/World/Client/WorldClient.cs | C P<S | Packet Read Error: Index was outside the bounds of the array.
   at HermesProxy.World.PlayerQuestTracker.WriteAllCompletedIntoArray(Nullable`1[] dest)
   at HermesProxy.World.Client.WorldClient.HandleUpdateObject(WorldPacket packet)
   at HermesProxy.World.Client.WorldClient.HandleCompressedUpdateObject(WorldPacket packet)
   at HermesProxy.World.Client.WorldClient.HandlePacket(WorldPacket packet)
   at HermesProxy.World.Client.WorldClient.ReceiveCallback(IAsyncResult AR)
```

**Game Server**
Everlook

**Hermes Proxy Version**
Latest release for Linux Ubuntu (v3.2 https://github.com/WowLegacyCore/HermesProxy/commit/b0dcbb87248df82c74f95fcb92c9dc67b57c8b52)
Arctium launched through Steam Proton (Experimental)

**Comment by arm358** [comment]
Seem to have fixed it by re-downloading Hermes

**Comment by 0blu** [comment]
Are you super sure you have Hermes 3.2?
I thought I fixed this bug
