### ISSUE TITLE
Hermes crash on login 

### ISSUE THREAD

**Issue by arm358** [WowLegacyCore/HermesProxy#112]
**Describe the bug**
Sometimes when attempting to log in Hermes crashes with the following exception. Do not see any type of pattern for the issue. Quitting Hermes and restarting the proxy usually fixes it, but sometimes I have to do it multiple times.
```
17:28:33 |  Server  | BnetTcpSession | Accepting connection from 127.0.0.1:51062.
17:28:34 |  Network | AuthClient | C P>S | Connecting to auth server... (realmlist addr: 51.91.104.108:3724)
17:28:34 |  Network | AuthClient | Authentication succeeded!
Unhandled exception. Google.Protobuf.InvalidProtocolBufferException: Protocol message contained an invalid tag (zero).
   at Google.Protobuf.CodedInputStream.ReadTag()
   at Bgs.Protocol.Account.V1.GetAccountStateRequest.MergeFrom(CodedInputStream input) in /home/runner/work/HermesProxy/Framework/Proto/AccountService.cs:line 1270
   at BNetServer.Services.BnetServices.ServiceManager.Invoke(UInt32 serviceId, OriginalHash serviceHash, UInt32 methodId, UInt32 requestToken, CodedInputStream stream)
   at BNetServer.Networking.BnetTcpSession.ReadHandler(Byte[] data, Int32 receivedLength)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object )
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback )
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext , Action`1 , TState& )
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
Aborted (core dumped)
```

**Game Server**
Everlook

**Hermes Proxy Version**
Linux Ubuntu v3.2 https://github.com/WowLegacyCore/HermesProxy/commit/b0dcbb87248df82c74f95fcb92c9dc67b57c8b52
Arctium launched through Steam Proton (Experimental)

**Comment by Fabi** [comment]
Most like the same: https://github.com/CypherCore/CypherCore/commit/a30e1d230f481468e1aff910b1d0e308653f3630

**Comment by 0blu** [comment]
Yeah, thx, I was already suspicious about this code and fixed it exactly like this it in my local repo.
