### ISSUE TITLE
Specific character log in issue

### ISSUE THREAD

**Issue by Nexuseryy** [WowLegacyCore/HermesProxy#274]
Hello! So I have recently bumped into an issue. One of my characters got disconnected and is unable to log in with this error message - Error   | WorldClient     | C P<S | Packet Read Error: Unable to read beyond the end of the stream.
   at System.IO.BinaryReader.InternalRead(Int32 )
   at System.IO.BinaryReader.ReadUInt32()
   at HermesProxy.World.Client.WorldClient.HandleInitWorldStates(WorldPacket packet)
   at HermesProxy.World.Client.WorldClient.HandlePacket(WorldPacket packet)
   at HermesProxy.World.Client.WorldClient.ReceiveLoop()

Other characters can log in just fine.

Game Server - moonwell 5xrealm
Hermes Proxy Version - 3.7(Last release)
Client version - 2.5.3

**Comment by Nexuseryy** [comment]
Ok so I figured out the issue most likely revolves around flight master in game. The server I play on is not perfect so that mighty be the issue. Also in 2.4.3 you wont see request stop option when you fly whilst in 2.5.3 you will and I think I used it, which potentially caused the issue. But its hard to say, it would still be great if you looked into the error and could figure something more.
