### ISSUE TITLE
Crash: Mouse hover over unsigned guild charter

### ISSUE THREAD

**Issue by Akorax** [WowLegacyCore/HermesProxy#277]
**Describe the bug**
After purchasing a guild charter, if you hover over the item in your inventory with your mouse cursor your client will crash.

**Game Server**
SPP Repack, CMaNGOS, vanilla 1.12 with 1.14.2 client, all updated 230226 (today).

**Hermes Proxy Version**
2023-01-30 *official* 3.7.0

**Error message**
```
10:42:38 |  Error   | WorldClient     | C P<S | Packet Read Error: Unable to read beyond the end of the stream.
   at System.IO.BinaryReader.InternalRead(Int32 )
   at System.IO.BinaryReader.ReadUInt32()
   at HermesProxy.World.Client.WorldClient.HandlePetitionQueryResponse(WorldPacket packet)
   at HermesProxy.World.Client.WorldClient.HandlePacket(WorldPacket packet)
   at HermesProxy.World.Client.WorldClient.ReceiveLoop()
```

**Comment by CaptainJaySolo** [comment]
I have the same issue when using the HermesProxy.
After purchasing a guild charter, once it's in the inventory, hovering the mouse over the charter causes the game to disconnect with the same error as above;

10:42:38 |  Error   | WorldClient     | C P<S | Packet Read Error: Unable to read beyond the end of the stream.
   at System.IO.BinaryReader.InternalRead(Int32 )
   at System.IO.BinaryReader.ReadUInt32()
   at HermesProxy.World.Client.WorldClient.HandlePetitionQueryResponse(WorldPacket packet)
   at HermesProxy.World.Client.WorldClient.HandlePacket(WorldPacket packet)
   at HermesProxy.World.Client.WorldClient.ReceiveLoop()

**Comment by Exxenoz** [comment]
> I have the same issue when using the HermesProxy. After purchasing a guild charter, once it's in the inventory, hovering the mouse over the charter causes the game to disconnect with the same error as above;
> 
> 10:42:38 | Error | WorldClient | C P<S | Packet Read Error: Unable to read beyond the end of the stream. at System.IO.BinaryReader.InternalRead(Int32 ) at System.IO.BinaryReader.ReadUInt32() at HermesProxy.World.Client.WorldClient.HandlePetitionQueryResponse(WorldPacket packet) at HermesProxy.World.Client.WorldClient.HandlePacket(WorldPacket packet) at HermesProxy.World.Client.WorldClient.ReceiveLoop()

The following PR fixes the above error: https://github.com/cmangos/mangos-classic/pull/537
