### ISSUE TITLE
when the character gets new quest items, he will be forced to log off

### ISSUE THREAD

**Issue by howarduong** [WowLegacyCore/HermesProxy#28]
You did very well. Thank you so much for your dedication here. I changed the output port of the proxy to 8080
In the process of playing, when the character gets new quest items, he will be forced to log off. This is the process log, please take a look
[15:08:58](https://www.youtube.com/watch?v=vAFMiQjdhRM&t=43200s) | Warning | WorldSocket | No handler for opcode CMSG_GET_UNDELETE_CHARACTER_COOLDOWN_STATUS (14052)
[15:08:58](https://www.youtube.com/watch?v=vAFMiQjdhRM&t=43200s) | Warning | WorldSocket | No handler for opcode CMSG_BATTLE_PAY_GET_PURCHASE_LIST (14018)
[15:08:58](https://www.youtube.com/watch?v=vAFMiQjdhRM&t=43200s) | Warning | WorldSocket | No handler for opcode CMSG_BATTLE_PAY_GET_PRODUCT_LIST (14017)
[15:08:58](https://www.youtube.com/watch?v=vAFMiQjdhRM&t=43200s) | Warning | WorldSocket | No handler for opcode CMSG_UPDATE_VAS_PURCHASE_STATES (14072)
[15:08:58](https://www.youtube.com/watch?v=vAFMiQjdhRM&t=43200s) | Error   | AuthClient | Socket Closed By Server
[15:09:05](https://www.youtube.com/watch?v=vAFMiQjdhRM&t=43200s) | Warning | WorldSocket | No handler for opcode CMSG_BATTLENET_REQUEST (14074)
[15:09:05](https://www.youtube.com/watch?v=vAFMiQjdhRM&t=43200s) | Warning | WorldSocket | No handler for opcode CMSG_GET_ACCOUNT_CHARACTER_LIST (14012)
[15:09:05](https://www.youtube.com/watch?v=vAFMiQjdhRM&t=43200s) | Warning | WorldSocket | No handler for opcode CMSG_BATTLE_PAY_GET_PURCHASE_LIST (14018)
[15:09:16](https://www.youtube.com/watch?v=vAFMiQjdhRM&t=43200s) | Network | WorldSocketManager | Instance socket open.
[15:09:16](https://www.youtube.com/watch?v=vAFMiQjdhRM&t=43200s) | Server  | WorldSocket | Client has connected to the instance server.
[15:09:16](https://www.youtube.com/watch?v=vAFMiQjdhRM&t=43200s) | Warning | WorldSocket | No handler for opcode CMSG_VIOLENCE_LEVEL (12680)
[15:09:16](https://www.youtube.com/watch?v=vAFMiQjdhRM&t=43200s) | Warning | WorldSocket | No handler for opcode CMSG_QUEUED_MESSAGES_END (14188)
[15:09:18](https://www.youtube.com/watch?v=vAFMiQjdhRM&t=43200s) | Warning | WorldClient | No handler for opcode SMSG_SET_REST_START (542)
[15:09:18](https://www.youtube.com/watch?v=vAFMiQjdhRM&t=43200s) | Warning | WorldSocket | No handler for opcode CMSG_REQUEST_CATEGORY_COOLDOWNS (12673)
[15:09:18](https://www.youtube.com/watch?v=vAFMiQjdhRM&t=43200s) | Warning | WorldSocket | No handler for opcode CMSG_MOVE_INIT_ACTIVE_MOVER_COMPLETE (14914)
[15:09:18](https://www.youtube.com/watch?v=vAFMiQjdhRM&t=43200s) | Warning | WorldSocket | No handler for opcode CMSG_QUERY_QUEST_COMPLETION_NPCS (12664)
[15:09:18](https://www.youtube.com/watch?v=vAFMiQjdhRM&t=43200s) | Warning | WorldSocket | No handler for opcode CMSG_LFG_LIST_GET_STATUS (13836)
[15:09:19](https://www.youtube.com/watch?v=vAFMiQjdhRM&t=43200s) | Warning | WorldSocket | No handler for opcode CMSG_REQUEST_FORCED_REACTIONS (12807)
[15:09:19](https://www.youtube.com/watch?v=vAFMiQjdhRM&t=43200s) | Warning | WorldSocket | No handler for opcode CMSG_CALENDAR_GET_NUM_PENDING (13948)
[15:09:19](https://www.youtube.com/watch?v=vAFMiQjdhRM&t=43200s) | Warning | WorldSocket | No handler for opcode CMSG_BATTLE_PET_REQUEST_JOURNAL (13861)
[15:09:19](https://www.youtube.com/watch?v=vAFMiQjdhRM&t=43200s) | Warning | WorldSocket | No handler for opcode CMSG_QUERY_COUNTDOWN_TIMER (12715)
[15:09:19](https://www.youtube.com/watch?v=vAFMiQjdhRM&t=43200s) | Warning | WorldClient | No handler for opcode SMSG_SPELL_EXECUTE_LOG (588)
[15:09:20](https://www.youtube.com/watch?v=vAFMiQjdhRM&t=43200s) | Warning | WorldSocket | No handler for opcode CMSG_GUILD_SET_ACHIEVEMENT_TRACKING (12399)
[15:09:21](https://www.youtube.com/watch?v=vAFMiQjdhRM&t=43200s) | Warning | WorldSocket | No handler for opcode CMSG_GM_TICKET_GET_CASE_STATUS (13967)
[15:09:26](https://www.youtube.com/watch?v=vAFMiQjdhRM&t=43200s) | Warning | WorldSocket | No handler for opcode CMSG_REQUEST_CEMETERY_LIST (12665)
[15:10:34](https://www.youtube.com/watch?v=vAFMiQjdhRM&t=43200s) | Warning | WorldSocket | No handler for opcode CMSG_REPORT_CLIENT_VARIABLES (14086)
[15:10:34](https://www.youtube.com/watch?v=vAFMiQjdhRM&t=43200s) | Warning | WorldSocket | No handler for opcode CMSG_REPORT_ENABLED_ADDONS (14085)
[15:10:34](https://www.youtube.com/watch?v=vAFMiQjdhRM&t=43200s) | Warning | WorldSocket | No handler for opcode CMSG_REPORT_KEYBINDING_EXECUTION_COUNTS (14087)
[15:10:35](https://www.youtube.com/watch?v=vAFMiQjdhRM&t=43200s) | Warning | WorldSocket | No handler for opcode CMSG_VIOLENCE_LEVEL (12680)
[15:10:35](https://www.youtube.com/watch?v=vAFMiQjdhRM&t=43200s) | Warning | WorldSocket | No handler for opcode CMSG_BATTLE_PAY_GET_PURCHASE_LIST (14018)
[15:10:36](https://www.youtube.com/watch?v=vAFMiQjdhRM&t=43200s) | Warning | WorldSocket | No handler for opcode CMSG_REQUEST_FORCED_REACTIONS (12807)
[15:10:36](https://www.youtube.com/watch?v=vAFMiQjdhRM&t=43200s) | Warning | WorldSocket | No handler for opcode CMSG_QUERY_QUEST_COMPLETION_NPCS (12664)
[15:10:36](https://www.youtube.com/watch?v=vAFMiQjdhRM&t=43200s) | Warning | WorldSocket | No handler for opcode CMSG_REQUEST_FORCED_REACTIONS (12807)
[15:10:36](https://www.youtube.com/watch?v=vAFMiQjdhRM&t=43200s) | Warning | WorldSocket | No handler for opcode CMSG_LFG_LIST_GET_STATUS (13836)
[15:10:36](https://www.youtube.com/watch?v=vAFMiQjdhRM&t=43200s) | Warning | WorldSocket | No handler for opcode CMSG_BATTLE_PET_REQUEST_JOURNAL (13861)
[15:10:37](https://www.youtube.com/watch?v=vAFMiQjdhRM&t=43200s) | Warning | WorldSocket | No handler for opcode CMSG_QUERY_COUNTDOWN_TIMER (12715)
[15:10:37](https://www.youtube.com/watch?v=vAFMiQjdhRM&t=43200s) | Warning | WorldSocket | No handler for opcode CMSG_GM_TICKET_GET_CASE_STATUS (13967)
[15:10:44](https://www.youtube.com/watch?v=vAFMiQjdhRM&t=43200s) | Warning | WorldSocket | No handler for opcode CMSG_REPORT_CLIENT_VARIABLES (14086)
[15:10:44](https://www.youtube.com/watch?v=vAFMiQjdhRM&t=43200s) | Warning | WorldSocket | No handler for opcode CMSG_REPORT_ENABLED_ADDONS (14085)
[15:10:44](https://www.youtube.com/watch?v=vAFMiQjdhRM&t=43200s) | Warning | WorldSocket | No handler for opcode CMSG_REPORT_KEYBINDING_EXECUTION_COUNTS (14087)
[15:10:44](https://www.youtube.com/watch?v=vAFMiQjdhRM&t=43200s) | Warning | WorldSocket | No handler for opcode CMSG_VIOLENCE_LEVEL (12680)
[15:10:44](https://www.youtube.com/watch?v=vAFMiQjdhRM&t=43200s) | Warning | WorldSocket | No handler for opcode CMSG_BATTLE_PAY_GET_PURCHASE_LIST (14018)
[15:10:46](https://www.youtube.com/watch?v=vAFMiQjdhRM&t=43200s) | Warning | WorldSocket | No handler for opcode CMSG_REQUEST_FORCED_REACTIONS (12807)
[15:10:46](https://www.youtube.com/watch?v=vAFMiQjdhRM&t=43200s) | Warning | WorldSocket | No handler for opcode CMSG_QUERY_QUEST_COMPLETION_NPCS (12664)
[15:10:46](https://www.youtube.com/watch?v=vAFMiQjdhRM&t=43200s) | Warning | WorldSocket | No handler for opcode CMSG_LFG_LIST_GET_STATUS (13836)
[15:10:46](https://www.youtube.com/watch?v=vAFMiQjdhRM&t=43200s) | Warning | WorldSocket | No handler for opcode CMSG_REQUEST_FORCED_REACTIONS (12807)
[15:10:46](https://www.youtube.com/watch?v=vAFMiQjdhRM&t=43200s) | Warning | WorldSocket | No handler for opcode CMSG_BATTLE_PET_REQUEST_JOURNAL (13861)
[15:10:46](https://www.youtube.com/watch?v=vAFMiQjdhRM&t=43200s) | Warning | WorldSocket | No handler for opcode CMSG_QUERY_COUNTDOWN_TIMER (12715)
[15:10:47](https://www.youtube.com/watch?v=vAFMiQjdhRM&t=43200s) | Warning | WorldSocket | No handler for opcode CMSG_GM_TICKET_GET_CASE_STATUS (13967)
[15:11:36](https://www.youtube.com/watch?v=vAFMiQjdhRM&t=43200s) | Warning | WorldClient | No handler for opcode SMSG_SPELL_EXECUTE_LOG (588)
[15:11:39](https://www.youtube.com/watch?v=vAFMiQjdhRM&t=43200s) | Warning | WorldClient | No handler for opcode SMSG_SPELL_EXECUTE_LOG (588)
[15:12:57](https://www.youtube.com/watch?v=vAFMiQjdhRM&t=43200s) | Warning | WorldSocket | No handler for opcode CMSG_QUERY_QUEST_COMPLETION_NPCS (12664)
[15:13:13](https://www.youtube.com/watch?v=vAFMiQjdhRM&t=43200s) | Warning | WorldSocket | No handler for opcode CMSG_QUERY_QUEST_COMPLETION_NPCS (12664)
[15:14:10](https://www.youtube.com/watch?v=vAFMiQjdhRM&t=43200s) | Error   | WorldClient | Packet Read Error: Nullable object must have a value.
   at System.Nullable`1.get_Value()
   at HermesProxy.World.Client.WorldClient.HandleItemPushResult(WorldPacket packet) in C:\Users\ratko\Desktop\source\CypherProxy\HermesProxy\HermesProxy\World\Client\PacketHandlers\ItemHandler.cs:line 34
   at HermesProxy.World.Client.WorldClient.HandlePacket(WorldPacket packet) in C:\Users\ratko\Desktop\source\CypherProxy\HermesProxy\HermesProxy\World\Client\WorldClient.cs:line 387
   at HermesProxy.World.Client.WorldClient.ReceiveCallback(IAsyncResult AR) in C:\Users\ratko\Desktop\source\CypherProxy\HermesProxy\HermesProxy\World\Client\WorldClient.cs:line 216
[15:14:17](https://www.youtube.com/watch?v=vAFMiQjdhRM&t=43200s) | Server  | Session | Accepting connection from 127.0.0.1:63812.
[15:14:18](https://www.youtube.com/watch?v=vAFMiQjdhRM&t=43200s) | Network | AuthClient | Connecting to auth server...
[15:14:18](https://www.youtube.com/watch?v=vAFMiQjdhRM&t=43200s) | Network | AuthClient | Authentication succeeded!
[15:14:18](https://www.youtube.com/watch?v=vAFMiQjdhRM&t=43200s) | Network | AuthClient | Received 1 realms.
[15:14:18](https://www.youtube.com/watch?v=vAFMiQjdhRM&t=43200s) | Server  | RealmManager | Added realm "Lightbringer" at 127.0.0.1:8085
[15:14:20](https://www.youtube.com/watch?v=vAFMiQjdhRM&t=43200s) | Network | WorldSocketManager | Instance socket open.
[15:14:20](https://www.youtube.com/watch?v=vAFMiQjdhRM&t=43200s) | Server  | WorldSocket | WorldSocket:HandleAuthSession: Client 'rick' authenticated successfully from 127.0.0.1:63816.
[15:14:20](https://www.youtube.com/watch?v=vAFMiQjdhRM&t=43200s) | Network | WorldClient | Connecting to world server...
[15:14:20](https://www.youtube.com/watch?v=vAFMiQjdhRM&t=43200s) | Network | WorldClient | Connection established!
[15:14:20](https://www.youtube.com/watch?v=vAFMiQjdhRM&t=43200s) | Network | WorldClient | Authentication succeeded!
[15:14:20](https://www.youtube.com/watch?v=vAFMiQjdhRM&t=43200s) | Warning | WorldSocket | No handler for opcode CMSG_GET_UNDELETE_CHARACTER_COOLDOWN_STATUS (14052)
[15:14:20](https://www.youtube.com/watch?v=vAFMiQjdhRM&t=43200s) | Warning | WorldSocket | No handler for opcode CMSG_BATTLE_PAY_GET_PURCHASE_LIST (14018)
[15:14:20](https://www.youtube.com/watch?v=vAFMiQjdhRM&t=43200s) | Warning | WorldSocket | No handler for opcode CMSG_BATTLE_PAY_GET_PRODUCT_LIST (14017)
[15:14:20](https://www.youtube.com/watch?v=vAFMiQjdhRM&t=43200s) | Warning | WorldSocket | No handler for opcode CMSG_UPDATE_VAS_PURCHASE_STATES (14072)
[15:14:20](https://www.youtube.com/watch?v=vAFMiQjdhRM&t=43200s) | Error   | AuthClient | Socket Closed By Server
[15:14:26](https://www.youtube.com/watch?v=vAFMiQjdhRM&t=43200s) | Warning | WorldSocket | No handler for opcode CMSG_BATTLENET_REQUEST (14074)
[15:14:27](https://www.youtube.com/watch?v=vAFMiQjdhRM&t=43200s) | Warning | WorldSocket | No handler for opcode CMSG_GET_ACCOUNT_CHARACTER_LIST (14012)
[15:14:27](https://www.youtube.com/watch?v=vAFMiQjdhRM&t=43200s) | Warning | WorldSocket | No handler for opcode CMSG_BATTLE_PAY_GET_PURCHASE_LIST (14018)
[15:14:27](https://www.youtube.com/watch?v=vAFMiQjdhRM&t=43200s) | Network | WorldSocketManager | Instance socket open.
[15:14:27](https://www.youtube.com/watch?v=vAFMiQjdhRM&t=43200s) | Server  | WorldSocket | Client has connected to the instance server.
[15:14:27](https://www.youtube.com/watch?v=vAFMiQjdhRM&t=43200s) | Warning | WorldSocket | No handler for opcode CMSG_VIOLENCE_LEVEL (12680)
[15:14:27](https://www.youtube.com/watch?v=vAFMiQjdhRM&t=43200s) | Warning | WorldSocket | No handler for opcode CMSG_QUEUED_MESSAGES_END (14188)
[15:14:28](https://www.youtube.com/watch?v=vAFMiQjdhRM&t=43200s) | Warning | WorldClient | No handler for opcode SMSG_SET_REST_START (542)
[15:14:28](https://www.youtube.com/watch?v=vAFMiQjdhRM&t=43200s) | Warning | WorldSocket | No handler for opcode CMSG_REQUEST_CATEGORY_COOLDOWNS (12673)
[15:14:29](https://www.youtube.com/watch?v=vAFMiQjdhRM&t=43200s) | Warning | WorldSocket | No handler for opcode CMSG_MOVE_INIT_ACTIVE_MOVER_COMPLETE (14914)
[15:14:29](https://www.youtube.com/watch?v=vAFMiQjdhRM&t=43200s) | Warning | WorldSocket | No handler for opcode CMSG_LFG_LIST_GET_STATUS (13836)
[15:14:29](https://www.youtube.com/watch?v=vAFMiQjdhRM&t=43200s) | Warning | WorldSocket | No handler for opcode CMSG_QUERY_QUEST_COMPLETION_NPCS (12664)
[15:14:29](https://www.youtube.com/watch?v=vAFMiQjdhRM&t=43200s) | Warning | WorldSocket | No handler for opcode CMSG_CALENDAR_GET_NUM_PENDING (13948)
[15:14:29](https://www.youtube.com/watch?v=vAFMiQjdhRM&t=43200s) | Warning | WorldSocket | No handler for opcode CMSG_REQUEST_FORCED_REACTIONS (12807)
[15:14:29](https://www.youtube.com/watch?v=vAFMiQjdhRM&t=43200s) | Warning | WorldSocket | No handler for opcode CMSG_BATTLE_PET_REQUEST_JOURNAL (13861)
[15:14:29](https://www.youtube.com/watch?v=vAFMiQjdhRM&t=43200s) | Warning | WorldSocket | No handler for opcode CMSG_QUERY_COUNTDOWN_TIMER (12715)
[15:14:29](https://www.youtube.com/watch?v=vAFMiQjdhRM&t=43200s) | Warning | WorldSocket | No handler for opcode CMSG_GUILD_SET_ACHIEVEMENT_TRACKING (12399)
[15:14:30](https://www.youtube.com/watch?v=vAFMiQjdhRM&t=43200s) | Warning | WorldSocket | No handler for opcode CMSG_GM_TICKET_GET_CASE_STATUS (13967)
[15:14:32](https://www.youtube.com/watch?v=vAFMiQjdhRM&t=43200s) | Warning | WorldSocket | No handler for opcode CMSG_REQUEST_CEMETERY_LIST (12665)
[15:15:01](https://www.youtube.com/watch?v=vAFMiQjdhRM&t=43200s) | Warning | WorldSocket | No handler for opcode CMSG_DISCARDED_TIME_SYNC_ACKS (14909)
[15:15:01](https://www.youtube.com/watch?v=vAFMiQjdhRM&t=43200s) | Warning | WorldSocket | No handler for opcode CMSG_REPORT_CLIENT_VARIABLES (14086)
[15:15:02](https://www.youtube.com/watch?v=vAFMiQjdhRM&t=43200s) | Warning | WorldSocket | No handler for opcode CMSG_REPORT_ENABLED_ADDONS (14085)
[15:15:02](https://www.youtube.com/watch?v=vAFMiQjdhRM&t=43200s) | Warning | WorldSocket | No handler for opcode CMSG_REPORT_KEYBINDING_EXECUTION_COUNTS (14087)

**Comment by ratkosrb** [comment]
You are using an old version of the proxy. This bug was already fixed. Download the newer release.

https://github.com/WowLegacyCore/HermesProxy/releases/tag/v2.0

**Comment by howarduong** [comment]
Thank you very much for your dedication. This work is great,

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2022年5月26日 17:01
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [WowLegacyCore/HermesProxy] when the character gets new quest items, he will be forced to log off (Issue #28)


You are using an old version of the proxy. This bug was already fixed. Download the newer release.

https://github.com/WowLegacyCore/HermesProxy/releases/tag/v2.0

―
