### ISSUE TITLE
priest character lvl 60 can not log in, with error report

### ISSUE THREAD

**Issue by chemhunter** [WowLegacyCore/HermesProxy#289]
**Describe the bug**
A priest character lvl 60 can not log in, but another lvl 12 warrior character under the same account can log in normally.
I tried disabling all addons, deleting the WTF folder, deleting wdb folder, but all not worked. 
When I download the client v1.12, the priest character  lvl 60 can log in, that means there is no problem with my account.
The error is reported as follows:
`   Error   | WorldClient     | C P<S | Packet Read Error: Unable to read beyond the end of the stream.
   at System.IO.BinaryReader.InternalRead(Int32 )
   at System.IO.BinaryReader.ReadUInt64()
   at HermesProxy.World.Server.AccountDataManager.LoadData(WowGuid128 guid, UInt32 type)
   at HermesProxy.World.Server.AccountDataManager.LoadAllData(WowGuid128 guid)
   at HermesProxy.World.Server.WorldSocket.SendAccountDataTimes()
   at HermesProxy.World.Client.WorldClient.HandleAccountDataTimes(WorldPacket packet)
   at HermesProxy.World.Client.WorldClient.HandlePacket(WorldPacket packet)
   at HermesProxy.World.Client.WorldClient.ReceiveLoop()`

**Game Server**
1.12 Everlook

**Hermes Proxy Version**
3.7

![图像 268](https://user-images.githubusercontent.com/12853323/226807080-a2711924-fe25-41b2-9ac8-b3c3619e96f9.png)

**Comment by ratkosrb** [comment]
There is something wrong with your saved account data. If you delete the AccountData folder in Hermes it may be fixed, but you will lose keybinds, macros and other settings.
