### ISSUE TITLE
You can enter the character selection page, but you cannot log in to the game. After logging into the Jinjin game, the broken link is displayed!

### ISSUE THREAD

**Issue by 1469853656** [WowLegacyCore/HermesProxy#296]
Version 2.5.3

17:58:02 |  Server  | Server          | Starting Hermes Proxy...
17:58:02 |  Server  | Server          | Version 2023-01-30 *official* 3.7.0
17:58:02 |  Server  | Server          | Modern (Client) Build: V2_5_3_42328
17:58:02 |  Server  | Server          | Legacy (Server) Build: V2_4_3_8606
17:58:02 |  Storage | GameData        | Loading data files...
17:58:02 |  Server  | VersionChecker  | Loaded 1059 legacy opcodes.
17:58:03 |  Server  | VersionChecker  | Loaded 1727 modern opcodes.
17:58:03 |  Storage | GameData        | Finished loading data.
17:58:03 |  Network | Server          | External IP: 127.0.0.1
17:58:03 |  Server  | Server          | Starting BnetTcpSession service on 127.0.0.1:1119...
17:58:03 |  Network | NetworkThread   | Network Thread Starting
17:58:03 |  Server  | Server          | Starting BnetRestApiSession service on 127.0.0.1:8081...
17:58:03 |  Network | NetworkThread   | Network Thread Starting
17:58:03 |  Server  | Server          | Starting RealmSocket service on 127.0.0.1:8084...
17:58:03 |  Network | NetworkThread   | Network Thread Starting
17:58:03 |  Server  | Server          | Starting WorldSocket service on 127.0.0.1:8086...
17:58:03 |  Network | NetworkThread   | Network Thread Starting
17:58:24 |  Server  | BnetTcpSession  | Accepting connection from 127.0.0.1:13415.
17:58:25 |  Network | AuthClient      | C P>S | Connecting to auth server... (realmlist addr: 192.168.128.8:3724) (resolved as: 192.168.128.8:3724)
17:58:25 |  Network | AuthClient      | Authentication succeeded!
17:58:25 |  Server  | AuthClient      | Requesting RealmList update for ADMIN
17:58:25 |  Network | AuthClient      | Received 1 realms.
17:58:25 |  Server  | RealmManager    | Added realm "月亮之井TBC" at 192.168.128.8:8086
17:58:25 |  Server  | WorldSocket     | WorldSocket:HandleAuthSession: Client 'ADMIN' authenticated successfully from 127.0.0.1:13419.
17:58:25 |  Network | WorldClient     | Connecting to world server...
17:58:25 |  Network | WorldClient     | Connection established!
17:58:25 |  Network | WorldClient     | Authentication succeeded!
17:58:26 |  Warning | WorldSocket     | C>P S | No handler for opcode CMSG_GET_UNDELETE_CHARACTER_COOLDOWN_STATUS (14053) (Got unknown packet from ModernClient)
17:58:26 |  Warning | WorldSocket     | C>P S | No handler for opcode CMSG_BATTLE_PAY_GET_PURCHASE_LIST (14019) (Got unknown packet from ModernClient)
17:58:26 |  Warning | WorldSocket     | C>P S | No handler for opcode CMSG_BATTLE_PAY_GET_PRODUCT_LIST (14018) (Got unknown packet from ModernClient)
17:58:26 |  Warning | WorldSocket     | C>P S | No handler for opcode CMSG_UPDATE_VAS_PURCHASE_STATES (14073) (Got unknown packet from ModernClient)
17:58:26 |  Error   | AuthClient      | C P<S | Socket Closed By Server
17:58:26 |  Warning | BnetServices    | [WorldSocket][127.0.0.1:13419, Account: ADMIN, Game account: ADMIN] Client requested service ResourcesService/m:1 but this service is not implemented?
17:58:34 |  Warning | WorldSocket     | C>P S | No handler for opcode CMSG_BATTLE_PAY_GET_PURCHASE_LIST (14019) (Got unknown packet from ModernClient)
17:58:35 |  Server  | WorldSocket     | Client has connected to the instance server.
17:58:35 |  Warning | WorldSocket     | C>P S | No handler for opcode CMSG_VIOLENCE_LEVEL (12680) (Got unknown packet from ModernClient)
17:58:35 |  Warning | WorldSocket     | C>P S | No handler for opcode CMSG_QUEUED_MESSAGES_END (14188) (Got unknown packet from ModernClient)
17:58:36 |  Error   | WorldClient     | C P<S | Packet Read Error: The output char buffer is too small to contain the decoded characters, encoding 'Unicode (UTF-8)' fallback 'System.Text.DecoderReplacementFallback'. (Parameter 'chars')
   at System.Text.Encoding.ThrowCharsOverflow(DecoderNLS , Boolean )
   at System.Text.Encoding.GetCharsWithFallback(ReadOnlySpan`1 , Int32 , Span`1 , Int32 , DecoderNLS )
   at System.Text.UTF8Encoding.GetCharsWithFallback(ReadOnlySpan`1 , Int32 , Span`1 , Int32 , DecoderNLS )
   at System.Text.Encoding.GetCharsWithFallback(Byte* , Int32 , Char* , Int32 , Int32 , Int32 , DecoderNLS )
   at System.Text.Encoding.GetChars(Byte* , Int32 , Char* , Int32 , DecoderNLS )
   at System.Text.Decoder.GetChars(ReadOnlySpan`1 , Span`1 , Boolean )
   at System.IO.BinaryReader.Read()
   at System.IO.BinaryReader.ReadChar()
   at Framework.IO.ByteBuffer.ReadCString() in D:\a\HermesProxy\Framework\IO\ByteBuffer.cs:line 122
   at HermesProxy.World.Client.WorldClient.HandleMotd(WorldPacket packet)
   at HermesProxy.World.Client.WorldClient.HandlePacket(WorldPacket packet)
   at HermesProxy.World.Client.WorldClient.ReceiveLoop()

**Comment by ratkosrb** [comment]
The error is in the MOTD (message of the day) packet, which shows a server message in the chat after you login.
