### ISSUE TITLE
StartNetwork failed to Start AsyncAcceptor // Failed to start BnetTcpSession service

### ISSUE THREAD

**Issue by kaydeay** [WowLegacyCore/HermesProxy#312]
Hi, I just changed the two lines in the code as suggested, using HermesProxy v3.7 with Windows. 
At my laptop it is working perfectly fine like this.
However, on my desktop i receive an error message:

10:49:31 |  Server  | Server          | Starting BnetTcpSession service on 127.0.0.1:1119...
10:49:31 |  Error   | AsyncAcceptor   | System.Net.Sockets.SocketException (10013): Der Zugriff auf einen Socket war aufgrund der Zugriffsrechte des Sockets unzulässig.
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError , String )
   at System.Net.Sockets.Socket.DoBind(EndPoint , SocketAddress )
   at System.Net.Sockets.Socket.Bind(EndPoint )
   at System.Net.Sockets.TcpListener.Start(Int32 )
   at System.Net.Sockets.TcpListener.Start()
   at Framework.Networking.AsyncAcceptor.Start(String ip, Int32 port) in D:\a\HermesProxy\Framework\Networking\AsyncAcceptor.cs:line 46
10:49:31 |  Network | SocketManager   | StartNetwork failed to Start AsyncAcceptor
Unhandled exception: System.Exception: Failed to start BnetTcpSession service
   at HermesProxy.Server.StartServer[TSocketType](IPEndPoint bindIp)
   at HermesProxy.Server.ServerMain(CommandLineArguments args)
   at HermesProxy.Program.<>c.<Main>b__0_0(InvocationContext ctx)
   at System.CommandLine.Invocation.AnonymousCommandHandler.Invoke(InvocationContext )
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__18_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__5_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>b__0>d.MoveNext()
Press enter to close

So somehow the socket cannot be used. It is probably used by another application? But I dont know how to troubleshoot best.
Any suggestions?
Thanks!
![Unbenannt](https://github.com/WowLegacyCore/HermesProxy/assets/134837145/7cc98611-6969-48f6-a23c-ad362f1bfbed)

**Comment by ratkosrb** [comment]
Make sure no other program is using port 1119.

**Comment by kkkkkkkkkkkkk-ddd** [comment]
Also make sure you ain't running program twice.

**Comment by iferalplay** [comment]
No other program is using port 1119,but i still receive this error.

**Comment by kissybaby** [comment]
I meet the same problem ,make sure no other program using port 1119,and restart computer ,close antivirus , no work ,any other suggestions?
