### ISSUE TITLE
ERROR: Packet Read Error: Unable to read beyond the end of the stream.

### ISSUE THREAD

**Issue by kalypto89** [WowLegacyCore/HermesProxy#326]
game disconnects randomly within 5 minutes of connecting to server
Game Server: smolderforge
client version used tbc 2.5.2 (40892)
hermes proxy version 3.7.0

error message:

21:04:12 |  Error   | WorldClient     | C P<S | Packet Read Error: Unable to read beyond the end of the stream.
   at System.IO.BinaryReader.InternalRead(Int32 )
   at System.IO.BinaryReader.ReadUInt32()
   at HermesProxy.World.Objects.MovementInfo.ReadMovementInfoLegacy(WorldPacket packet, GameSessionData gameState)
   at HermesProxy.World.Client.WorldClient.HandleMovementMessages(WorldPacket packet)
   at HermesProxy.World.Client.WorldClient.HandlePacket(WorldPacket packet)
   at HermesProxy.World.Client.WorldClient.ReceiveLoop()
![image](https://github.com/WowLegacyCore/HermesProxy/assets/116260914/09c96ddc-ebf4-446e-a1e3-ef013a9e6911)

**Comment by kalypto89** [comment]
bump please :) thanks @0blu
