### ISSUE TITLE
Disconnect upon applying Rogue posion.

### ISSUE THREAD

**Issue by Fearyii** [WowLegacyCore/HermesProxy#333]
**Describe the bug**
Using any rank of any rogue posion disconnects you on TBC, making it impossible to use in arenas which is really bad. (Happens on both MH/OH)

**Game Server**
Stormforge TBC

**Hermes Proxy Version**
Compiled on 07/22/2023 20:18:24. Brotalnia's latest version but this bug is on both versions of the Proxy.

Log:
03:36:29 | Error   | WorldClient | Packet Read Error: Specified argument was out of the range of valid values. (Parameter '0x00000500')
   at HermesProxy.World.HighGuidLegacy..ctor(HighGuidTypeLegacy high)
   at HermesProxy.World.WowGuid64..ctor(UInt64 id)
   at HermesProxy.World.WorldPacket.ReadPackedGuid()
   at HermesProxy.World.Client.WorldClient.HandleEnchantmentLog(WorldPacket packet)
   at HermesProxy.World.Client.WorldClient.HandlePacket(WorldPacket packet)
   at HermesProxy.World.Client.WorldClient.ReceiveCallback(IAsyncResult AR)
--- End of stack trace from previous location ---
   at HermesProxy.World.Client.WorldClient.ReceiveCallback(IAsyncResult AR)

**Comment by santaslittlehelper2** [comment]
Works just fine.  
Use proper cMangos server.
