### ISSUE TITLE
Looting something causes an Error from time to time: WorldClient | Packet Read Error: Nullable object must have a value.   

### ISSUE THREAD

**Issue by raderunner** [WowLegacyCore/HermesProxy#35]
First of all, great project! 

I get this error from time to time when I am looting something. I'm using auto loot from the client and faster auto loot from LeatrixPlus. 
WorldClient | Packet Read Error: Nullable object must have a value.   
`17:28:37 | Error   | WorldClient | Packet Read Error: Nullable object must have a value.                                                      at HermesProxy.World.Client.WorldClient.HandleItemPushResult(WorldPacket packet) in C:\Users\<>\Source\Repos\HermesProxy2\HermesProxy\World\Client\PacketHandlers\ItemHandler.cs:line 34                                                                                           at HermesProxy.World.Client.WorldClient.HandlePacket(WorldPacket packet) in C:\Users\<>\Source\Repos\HermesProxy2\HermesProxy\World\Client\WorldClient.cs:line 387                                                                                                                 at HermesProxy.World.Client.WorldClient.ReceiveCallback(IAsyncResult AR) in C:\Users\<>\Source\Repos\HermesProxy2\HermesProxy\World\Client\WorldClient.cs:line 189 `

**Comment by ratkosrb** [comment]
Already fixed. Download the latest release.
https://github.com/WowLegacyCore/HermesProxy/releases/download/v3.0/HermesProxy.Windows.27-05-2022.zip

**Comment by raderunner** [comment]
Ok, I'll try. I did clone and build the project a few hours ago, though...

**Comment by raderunner** [comment]
I think it's because I am using the Arctium Launcher Static Seed of the Hermes Repack 17-05-2022. I'm new to C++/C#, so I might have some issues with understanding things. When I build the HermesProxy Project in Visual Studio 2022 I don't get all the dlls that are in the release you have linked. When I extract the 27-05-2022 release into my WoW folder to override the old dlls from the 17-05-2022 repack, I get disconnected when I click on the realm. I'm using it with Light's Hope server. 

`18:14:05 | Error   | WorldSocket | WorldSocket.HandleAuthSession: Authentication failed for account: 1 ('admin') address: 127.0.0.1:50173                                                                                                       
18:14:05 | Error   | AuthClient | Socket Closed By Server  ` 

What should I do here? Use a new wow client and extract the hermes27.05.2022 release into it? How do I get the Arctium Launcher Static Seed for the 27.05.2022 version?

**Comment by ratkosrb** [comment]
The launcher is the same. And you're not supposed to extract Hermes into the game folder.

**Comment by raderunner** [comment]
Ok, got it to running now! I'll play for a while to see if I get this error again.

**Comment by raderunner** [comment]
Just got this one right now (I'm not using code because the ` was part of the exception).
19:01:08 | Error   | WorldClient | Packet Read Error: Nullable object must have a value.
   at System.Nullable`1.get_Value()
   at HermesProxy.World.Client.WorldClient.HandleItemPushResult(WorldPacket packet) in C:\Users\ratko\Desktop\source\CypherProxy\HermesProxy\HermesProxy\World\Client\PacketHandlers\ItemHandler.cs:line 34
   at HermesProxy.World.Client.WorldClient.HandlePacket(WorldPacket packet) in C:\Users\ratko\Desktop\source\CypherProxy\HermesProxy\HermesProxy\World\Client\WorldClient.cs:line 387
   at HermesProxy.World.Client.WorldClient.ReceiveCallback(IAsyncResult AR) in C:\Users\ratko\Desktop\source\CypherProxy\HermesProxy\HermesProxy\World\Client\WorldClient.cs:line 216

**Comment by ratkosrb** [comment]
Compile it in Debug, and then post exception, so hopefully it shows the actual line, instead of the beginning of the function.

**Comment by raderunner** [comment]
Teststeps:

- I started HermesProxy in Debug-Mode in Visual Studio with a breakpoint at line 34 of Itemhandler.cs
- I played a Rogue in the Human starting zone. 
- This error occurs for the first time during the red bandana quest
- In Visual Studio I get this error:  CS0246 https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs0246?f1url=%3FappId%3Droslyn%26k%3Dk(CS0246)
- It says it can't find the namespace dtItemPushResult

**Comment by ratkosrb** [comment]
That sounds like a compiler error, not a runtime exception.

**Comment by ratkosrb** [comment]
Show me a picture of HermesProxy right after you start it, and another of the function that begins at line 34 of ItemHandler.cs from Visual Studio.

**Comment by raderunner** [comment]
Yeah, that was just a typo. I think the nullpointer exception happens at line 75 of ItemHandler.cs:
`currentCount = (uint)logEntry.ObjectiveProgress[objective.StorageIndex];`

It's hard to debug, as the exception is only occuring very rarely when you pick up a quest item. I'm going to continue trying to verfiy this and post an update when it happens again.

**Comment by Luccifer** [comment]
Got the same case when you get the NEW quest and the lootable quest item will be the first one you found, so there are no quest items in bag, but this will be the first one, looks like the StorageIndex can be null\nil and there is no such index for code to safe execute, exception might help

**Comment by raderunner** [comment]
Just confirmed that sometimes `logEntry.ObjectiveProgress[objective.StorageIndex]` can be null for a StorageIndex when you pick up the first quest item. I think the problem is caused by UpdateHandler.cs in line 1026 onwards: 
```
questLog.ObjectiveProgress[0] = (byte)(rawValue & 0x3F);
questLog.ObjectiveProgress[1] = (byte)((rawValue & (0x3F << 6)) >> 6);
questLog.ObjectiveProgress[2] = (byte)((rawValue & (0x3F << 12)) >> 12);
questLog.ObjectiveProgress[3] = (byte)((rawValue & (0x3F << 18)) >> 18);
```
When I debugged this case all values of the array with index 0-3 were null.

**Comment by Luccifer** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/1053009/170841672-fcd7aec4-b67e-4314-bd72-bc51cb3d9afe.png)
Ok, to make a closer loook to a pproblem,, this issue happens when you are tryinng to loot the very first (order is not for quest but for the quantative) object item.

F.E.: trying to make quest in Gnomie starting location and on the quest with Frostmorne trolls, whenn you need to loot 3 places, so the first loot object will cause the critical exception, other - no, any order, but the very first one choosen by you - excepption
