### ISSUE TITLE
Stuck at login screen on "Connecting" with Steam GE-Proton-9-7 on Linux

### ISSUE THREAD

**Issue by svOOvzi** [WowLegacyCore/HermesProxy#371]
**Describe the bug**
I am running HermesProxy 3.10 and Arctium Launcher through Steam with `GE-Proton-9-7` on Arch Linux x86_64, kernel version `6.9.4-arch1-1`. I have the config set for the 1.14.0 client with the line `<add key="ClientBuild" value="40618" />` and the realmlist for everlook with the line `<add key="ServerAddress" value="logon.everlook.org" />` in the HermesProxy.config, and my config.wtf is pointed correctly with `SET portal "127.0.0.1"`. Arctium Launcher is running with arguments `--staticseed --version=ClassicEra`.

Now after successfully getting to the login screen and inputting my login details it gets stuck on "Connecting" and HermesProxy outputs the following error:

```
14:47:06 |  Server  | Server          | Starting Hermes Proxy...
14:47:06 |  Server  | Server          | Version 2023-10-19 *official* 3.10.0
14:47:06 |  Server  | Server          | Modern (Client) Build: V1_14_0_40618
14:47:06 |  Server  | Server          | Legacy (Server) Build: V1_12_1_5875
14:47:06 |  Storage | GameData        | Loading data files...
14:47:06 |  Server  | VersionChecker  | Loaded 833 legacy opcodes.
14:47:06 |  Server  | VersionChecker  | Loaded 1639 modern opcodes.
14:47:08 |  Storage | GameData        | Finished loading data.
14:47:08 |  Network | Server          | External IP: 127.0.0.1
14:47:08 |  Server  | Server          | Starting BnetTcpSession service on 127.0
.0.1:1119...
14:47:08 |  Network | NetworkThread   | Network Thread Starting
14:47:08 |  Server  | Server          | Starting BnetRestApiSession service on 1
27.0.0.1:8081...
14:47:08 |  Network | NetworkThread   | Network Thread Starting
14:47:08 |  Server  | Server          | Starting RealmSocket service on 127.0.0.
1:8084...
14:47:08 |  Network | NetworkThread   | Network Thread Starting
14:47:08 |  Server  | Server          | Starting WorldSocket service on 127.0.0.
1:8086...
14:47:08 |  Network | NetworkThread   | Network Thread Starting
14:47:39 |  Server  | BnetTcpSession  | Accepting connection from 127.0.0.1:4889
8.
14:47:39 |  Error   | SocketManager   | System.TypeInitializationException: The
type initializer for 'BNetServer.BnetServerCertificate' threw an exception.
 ---> System.Security.Cryptography.CryptographicException: PKCS12 (PFX) without
a supplied password has exceeded maximum allowed iterations. See https://go.micr
osoft.com/fwlink/?linkid=2233907 for more information.
 ---> Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException: Unk
nown error (0xc1000002)
   at Internal.NativeCrypto.Cng.BCryptOpenAlgorithmProvider(String , String , Op
enAlgorithmProviderFlags )
   at Internal.Cryptography.RC2BCryptModes.OpenRC2Algorithm(String , Int32 )
   at Internal.Cryptography.RC2BCryptModes.GetHandle(CipherMode , Int32 )
   at Internal.Cryptography.RC2Implementation.CreateTransformCore(CipherMode , P
addingMode , Byte[] , Int32 , Byte[] , Int32 , Int32 , Int32 , Boolean )
   at Internal.Cryptography.RC2Implementation.CreateTransform(Byte[] , Byte[] ,
Boolean )
   at Internal.Cryptography.RC2Implementation.CreateDecryptor(Byte[] , Byte[] )
   at System.Security.Cryptography.PasswordBasedEncryption.Decrypt(SymmetricAlgo
rithm , ReadOnlySpan`1 , ReadOnlySpan`1 , ReadOnlySpan`1 , Span`1 )
   at System.Security.Cryptography.PasswordBasedEncryption.Pkcs12PbeDecrypt(Algo
rithmIdentifierAsn , ReadOnlySpan`1 , HashAlgorithmName , SymmetricAlgorithm , R
eadOnlySpan`1 , Span`1 )
   at System.Security.Cryptography.PasswordBasedEncryption.Decrypt(AlgorithmIden
tifierAsn& , ReadOnlySpan`1 , ReadOnlySpan`1 , ReadOnlySpan`1 , Span`1 )
   at System.Security.Cryptography.Asn1.Pkcs12.PfxAsn.DecryptContentInfo(Content
InfoAsn , UInt32& )
   at System.Security.Cryptography.Asn1.Pkcs12.PfxAsn.CountTotalIterations()
   at System.Security.Cryptography.X509Certificates.X509Certificate.GetIteration
Count(ReadOnlySpan`1 )
   at System.Security.Cryptography.X509Certificates.X509Certificate.EnforceItera
tionCountLimit(ReadOnlySpan`1 , Boolean , Boolean )
   --- End of inner exception stack trace ---
   at System.Security.Cryptography.X509Certificates.X509Certificate.EnforceItera
tionCountLimit(ReadOnlySpan`1 , Boolean , Boolean )
   at Internal.Cryptography.Pal.CertificatePal.FromBlobOrFile(ReadOnlySpan`1 , S
tring , SafePasswordHandle , X509KeyStorageFlags )
   at Internal.Cryptography.Pal.CertificatePal.FromBlob(ReadOnlySpan`1 , SafePas
swordHandle , X509KeyStorageFlags )
   at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(ReadOn
lySpan`1 )
   at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(Byte[]
 )
   at System.Security.Cryptography.X509Certificates.X509Certificate2..ctor(Byte[
] )
   at BNetServer.BnetServerCertificate..cctor()
   --- End of inner exception stack trace ---
   at BNetServer.BnetServerCertificate.get_Certificate()
   at BNetServer.Networking.BnetTcpSession.Accept()
   at Framework.Networking.SocketManager`1.OnSocketOpen(Socket sock) in D:\a\Her
mesProxy\Framework\Networking\SocketManager.cs:line 84
```

In the error it suggests to go to `https://go.microsoft.com/fwlink/?linkid=2233907` for more information suggesting that there is an error with the .NET Framework.

I am unsure how to proceed and fix this login error. I do not have 2fa enabled on my everlook account.

Is anyone successfully using HermesProxy and Arctium Launcher to login to everlook with proton on linux?

**Game Server**
Everlook.org

**Hermes Proxy Version**
HermesProxy 3.10

**Comment by Tusam3** [comment]
Having the same issue.

**Comment by wormrunner** [comment]
same exact problem trying to connect to the Crusader Storm server in their test run.  Using winehq-staging 9.6.

**Comment by 6661620a** [comment]
same problem here on everlook on ubuntu 22.04

**Comment by 6661620a** [comment]
i managed to compile it on linux using the dotnet sdk from microsoft. that worked with the command provided in the linux compile script.
I can successfully log in and select my server but then I only see a black screen and two errors popping up in the logging output

```
HermesProxy/bin/release/ubuntu.16.04-x64/HermesProxy --config /home/user/Games/wow-everlook/WoWEverlook/HermesProxy/HermesProxy.config
18:19:17 |  Server  | Server          | Starting Hermes Proxy...
18:19:17 |  Server  | Server          | Version 2023-10-19 3.10.0
18:19:17 |  Storage | Server          | Switching working directory
18:19:17 |  Storage | Server          | Old: /home/user/git/HermesProxy
18:19:17 |  Storage | Server          | New: /home/user/git/HermesProxy/HermesProxy/bin/release/ubuntu.16.04-x64
18:19:18 |  Server  | Server          | Modern (Client) Build: V1_14_2_42597
18:19:18 |  Server  | Server          | Legacy (Server) Build: V1_12_1_5875
18:19:18 |  Storage | GameData        | Loading data files...
18:19:18 |  Server  | VersionChecker  | Loaded 833 legacy opcodes.
18:19:18 |  Server  | VersionChecker  | Loaded 1727 modern opcodes.
18:19:20 |  Storage | GameData        | Finished loading data.
18:19:20 |  Network | Server          | External IP: 127.0.0.1
18:19:20 |  Server  | Server          | Starting BnetTcpSession service on 127.0.0.1:1119...
18:19:20 |  Network | NetworkThread   | Network Thread Starting
18:19:20 |  Server  | Server          | Starting BnetRestApiSession service on 127.0.0.1:8081...
18:19:20 |  Network | NetworkThread   | Network Thread Starting
18:19:20 |  Server  | Server          | Starting RealmSocket service on 127.0.0.1:8084...
18:19:20 |  Network | NetworkThread   | Network Thread Starting
18:19:20 |  Server  | Server          | Starting WorldSocket service on 127.0.0.1:8086...
18:19:20 |  Network | NetworkThread   | Network Thread Starting
18:19:23 |  Server  | BnetTcpSession  | Accepting connection from 127.0.0.1:36416.
18:19:24 |  Network | AuthClient      | C P>S | Connecting to auth server... (realmlist addr: logon.everlook.org:3724) (resolved as: 37.59.30.120:3724)
18:19:24 |  Network | AuthClient      | Authentication succeeded!
18:19:24 |  Server  | AuthClient      | Requesting RealmList update for  <redacted>
18:19:24 |  Network | AuthClient      | Received 3 realms.
18:19:24 |  Server  | RealmManager    | Added realm "Everlook" at 37.59.30.120:8090
18:19:24 |  Server  | RealmManager    | Added realm "PTR" at 37.59.30.120:8087
18:19:24 |  Server  | RealmManager    | Added realm "Starfall" at 37.59.30.120:8099
18:19:27 |  Server  | WorldSocket     | WorldSocket:HandleAuthSession: Client ' <redacted>' authenticated successfully from 127.0.0.1:46288.
18:19:27 |  Network | WorldClient     | Connecting to world server...
18:19:27 |  Network | WorldClient     | World Server address 37.59.30.120:8099 resolved as 37.59.30.120:8099
18:19:27 |  Network | WorldClient     | Connection established!
18:19:27 |  Network | WorldClient     | Authentication succeeded!
18:19:27 |  Warning | WorldClient     | C P<S | No handler for opcode SMSG_WARDEN_DATA (742) (Got unknown packet from WorldServer)
18:19:27 |  Error   | AuthClient      | C P<S | Socket Closed By Server
18:19:27 |  Warning | WorldSocket     | C>P S | No handler for opcode CMSG_GET_UNDELETE_CHARACTER_COOLDOWN_STATUS (14053) (Got unknown packet from ModernClient)
18:19:27 |  Warning | WorldSocket     | C>P S | No handler for opcode CMSG_BATTLE_PAY_GET_PURCHASE_LIST (14019) (Got unknown packet from ModernClient)
18:19:27 |  Warning | WorldSocket     | C>P S | No handler for opcode CMSG_BATTLE_PAY_GET_PRODUCT_LIST (14018) (Got unknown packet from ModernClient)
18:19:27 |  Warning | WorldSocket     | C>P S | No handler for opcode CMSG_UPDATE_VAS_PURCHASE_STATES (14073) (Got unknown packet from ModernClient)
18:19:27 |  Warning | BnetServices    | [WorldSocket][127.0.0.1:46288, Account: <redacted>, Game account:  <redacted>] Client requested service ResourcesService/m:1 but this service is not implemented?
18:19:57 |  Error   | WorldClient     | C P<S | Socket Closed By GameWorldServer (header)

```

![image](https://github.com/WowLegacyCore/HermesProxy/assets/10408378/c0181391-2dd3-43d7-b1f0-9a2bf22fa5e8)

**Comment by ratkosrb** [comment]
The server you are connecting to has Warden enabled and it does not send the character list until the client has replied to the Warden packet, which Hermes cannot do unless you did your own implementation of Warden, since that is not provided.

**Comment by 6661620a** [comment]
i found a simple workaround by createding a tiny windows vm that only runs the proxy with the settings provided by everlook.org and just connect to it from my linux hosts that runs the wow classic client. not ideal but working :)

**Comment by karljohan122** [comment]
Same problem on Nobara KDE, Fedora

**Comment by collinpc123** [comment]
I'm not entirely familiar with Hermes or wow emulation in general but I was able to fix the issue by simply cloning the repo and building a proper linux binary. I don't know if this server has warden or not.

**Comment by karljohan122** [comment]
> I'm not entirely familiar with Hermes or wow emulation in general but I was able to fix the issue by simply cloning the repo and building a proper linux binary. I don't know if this server has warden or not.

How would you go about this? I'm pretty new to Linux

**Comment by collinpc123** [comment]
> > I'm not entirely familiar with Hermes or wow emulation in general but I was able to fix the issue by simply cloning the repo and building a proper linux binary. I don't know if this server has warden or not.
> 
> How would you go about this? I'm pretty new to Linux

Just clone the repo and build it. You'll have to install dotnet runtime and dotnet sdk through your package manager. Type dotnet to make sure it's installed. 

Then in the hermes repo in scripts folder copy the Linux build script and fix it to be a proper Linux build script (forward slash instead of back slash). Release binary and artifacts are in the build/bin folder. Should be able to run hermes directly from there.

**Comment by karljohan122** [comment]
For me doing `sudo dnf install dotnet-sdk-8.0` fixed the issue. I deleted the game files, extracted them again and added them to Lutris with a new prefix and it just worked.

**Comment by vclst** [comment]
Hi, same issue here with ArchLinux with Lutris.

**Comment by karljohan122** [comment]
> Hi, same issue here with ArchLinux with Lutris.

The guy who commented before me had the fix. Clone the HermesProxy repo with git and build the binary/exe from the scripts folder. Make sure you use forward slash in the script. In my case SoloCraft already had a HermesProxy build/folder included so I just copied the hermes config from there to the cloned repo and built the exe with the script and launched the game with that executable and it worked. Also make sure you have dotnet installed.

I think this issue can be closed as this can be fixed.

**Comment by karljohan122** [comment]
> I'm not entirely familiar with Hermes or wow emulation in general but I was able to fix the issue by simply cloning the repo and building a proper linux binary. I don't know if this server has warden or not.

Thank you, your solution worked. The server did have warden enabled but it does not seem to matter.

**Comment by vclst** [comment]
> > Hi, same issue here with ArchLinux with Lutris.
> 
> The guy who commented before me had the fix. Clone the HermesProxy repo with git and build the binary/exe from the scripts folder. Make sure you use forward slash in the script. In my case SoloCraft already had a HermesProxy build/folder included so I just copied the hermes config from there to the cloned repo and built the exe with the script and launched the game with that executable and it worked. Also make sure you have dotnet installed.
> 
> I think this issue can be closed as this can be fixed.

Thanks for the workaround, but can you provide a little more help please? I'm not very familiar with wine.

I cloned the repository, updated the path with / and tried to build HermesProxy with the command: `wine Build_Windows.bat` but it outputed an error:
`Can't recognize 'dotnet publish ../HermesProxy -p:PublishSingleFile=true -p:DebugType=None -p:DebugSymbols=false -r win-x64 /p:Configuration=Release /p:platform="x64" --self-contained' as an internal or external command, or batch script.`

I reckon the dotnet package is missing, and tried to install it with winetricks but nothing changed.

How did you manage to compile it?

**Comment by karljohan122** [comment]
> > > Hi, same issue here with ArchLinux with Lutris.
> > 
> > 
> > The guy who commented before me had the fix. Clone the HermesProxy repo with git and build the binary/exe from the scripts folder. Make sure you use forward slash in the script. In my case SoloCraft already had a HermesProxy build/folder included so I just copied the hermes config from there to the cloned repo and built the exe with the script and launched the game with that executable and it worked. Also make sure you have dotnet installed.
> > I think this issue can be closed as this can be fixed.
> 
> Thanks for the workaround, but can you provide a little more help please? I'm not very familiar with wine.
> 
> I cloned the repository, updated the path with / and tried to build HermesProxy with the command: `wine Build_Windows.bat` but it outputed an error: `Can't recognize 'dotnet publish ../HermesProxy -p:PublishSingleFile=true -p:DebugType=None -p:DebugSymbols=false -r win-x64 /p:Configuration=Release /p:platform="x64" --self-contained' as an internal or external command, or batch script.`
> 
> I reckon the dotnet package is missing, and tried to install it with winetricks but nothing changed.
> 
> How did you manage to compile it?

Okay so first of all don't build the Windows script, use the Linux one as you are on Linux. Second, don't build it with wine, cd into the scripts folder in the terminal and do ./Build_Linux.bat. Also don't install dotnet through winetricks but through the terminal(make sure you get both dotnet-sdk and dotnet-runtime). Also I would recommend adding the game to Lutris instead of running it through wine, use the locally installed game option(last option).

**Comment by vclst** [comment]
> Okay so first of all don't build the Windows script, use the Linux one as you are on Linux. Second, don't build it with wine, cd into the scripts folder in the terminal and do ./Build_Linux.bat. Also don't install dotnet through winetricks but through the terminal(make sure you get both dotnet-sdk and dotnet-runtime). Also I would recommend adding the game to Lutris instead of running it through wine, use the locally installed game option(last option).

Ok thanks - it was confusing for me because this is the first time I use wine, so I did not realize that there is no issue with having a Linux app and a Wine app working together.

So yep, I successfuly compile the HermesProxy and am able to connect.

Unfortunately, I have the same error as @6661620a  with a black screen with no characters after connecting to the server.

**Comment by collinpc123** [comment]
> > Okay so first of all don't build the Windows script, use the Linux one as you are on Linux. Second, don't build it with wine, cd into the scripts folder in the terminal and do ./Build_Linux.bat. Also don't install dotnet through winetricks but through the terminal(make sure you get both dotnet-sdk and dotnet-runtime). Also I would recommend adding the game to Lutris instead of running it through wine, use the locally installed game option(last option).
> 
> Ok thanks - it was confusing for me because this is the first time I use wine, so I did not realize that there is no issue with having a Linux app and a Wine app working together.
> 
> So yep, I successfuly compile the HermesProxy and am able to connect.
> 
> Unfortunately, I have the same error as @6661620a with a black screen with no characters after connecting to the server.

Are there any error messages or warnings? Did you actually start the hermes Linux binary with the proper config for your server? You're not still running the windows binary through wine? (I had to comment out the windows hermes in the start script for the server I'm playing on)

**Comment by vclst** [comment]
> Are there any error messages or warnings? Did you actually start the hermes Linux binary with the proper config for your server? You're not still running the windows binary through wine? (I had to comment out the windows hermes in the start script for the server I'm playing on)

Yep I copied every files except the .exe - I am able to connect to my account on server (Everlook) and to choose my realm. But then the client is unable to load the characters list. 

From what is wrote above, this is due to something with the warden and I'm afraid there is no way to fix that on Linux.

**Comment by vclst** [comment]
> i found a simple workaround by createding a tiny windows vm that only runs the proxy with the settings provided by everlook.org and just connect to it from my linux hosts that runs the wow classic client. not ideal but working :)

I'm interested if you have more information about how you did that - especially how to configure Linux to use the vm HermesProxy.

**Comment by collinpc123** [comment]
> > Are there any error messages or warnings? Did you actually start the hermes Linux binary with the proper config for your server? You're not still running the windows binary through wine? (I had to comment out the windows hermes in the start script for the server I'm playing on)
> 
> Yep I copied every files except the .exe - I am able to connect to my account on server (Everlook) and to choose my realm. But then the client is unable to load the characters list.
> 
> From what is wrote above, this is due to something with the warden and I'm afraid there is no way to fix that on Linux.

Warden should work fine. The server I'm playing on uses Warden. There's something wrong with your configuration. The .exe is a windows executable

**Comment by vclst** [comment]
> Warden should work fine. The server I'm playing on uses Warden. There's something wrong with your configuration. The .exe is a windows executable

TBH I have to idea - I know I am able to log to the right server but then I have errors.

Here are the full logs:
12:21:33 |  Server  | Server          | Starting Hermes Proxy...
12:21:33 |  Server  | Server          | Version 2023-10-19 3.10.0 dirty
12:21:33 |  Server  | Server          | Modern (Client) Build: V1_14_2_42597
12:21:33 |  Server  | Server          | Legacy (Server) Build: V1_12_1_5875
12:21:33 |  Storage | GameData        | Loading data files...
12:21:33 |  Server  | VersionChecker  | Loaded 833 legacy opcodes.
12:21:33 |  Server  | VersionChecker  | Loaded 1727 modern opcodes.
12:21:35 |  Storage | GameData        | Finished loading data.
12:21:35 |  Network | Server          | External IP: 127.0.0.1
12:21:35 |  Server  | Server          | Starting BnetTcpSession service on 127.0.0.1:1119...
12:21:35 |  Network | NetworkThread   | Network Thread Starting
12:21:35 |  Server  | Server          | Starting BnetRestApiSession service on 127.0.0.1:8081...
12:21:35 |  Network | NetworkThread   | Network Thread Starting
12:21:35 |  Server  | Server          | Starting RealmSocket service on 127.0.0.1:8084...
12:21:35 |  Network | NetworkThread   | Network Thread Starting
12:21:35 |  Server  | Server          | Starting WorldSocket service on 127.0.0.1:8086...
12:21:35 |  Network | NetworkThread   | Network Thread Starting
12:21:54 |  Server  | BnetTcpSession  | Accepting connection from 127.0.0.1:53584.
12:21:55 |  Network | AuthClient      | C P>S | Connecting to auth server... (realmlist addr: logon.everlook.org:3724) (resolved as: 37.59.30.120:3724)
12:21:55 |  Network | AuthClient      | Authentication succeeded!
12:21:55 |  Server  | AuthClient      | Requesting RealmList update for ACCOUNT_NAME
12:21:55 |  Network | AuthClient      | Received 3 realms.
12:21:55 |  Server  | RealmManager    | Added realm "Everlook" at 37.59.30.120:8090
12:21:55 |  Server  | RealmManager    | Added realm "PTR" at 37.59.30.120:8087
12:21:55 |  Server  | RealmManager    | Added realm "Starfall" at 37.59.30.120:8099
12:21:59 |  Server  | WorldSocket     | WorldSocket:HandleAuthSession: Client 'ACCOUNT_NAME' authenticated successfully from 127.0.0.1:55228.
12:22:00 |  Network | WorldClient     | Connecting to world server...
12:22:00 |  Network | WorldClient     | World Server address 37.59.30.120:8090 resolved as 37.59.30.120:8090
12:22:00 |  Network | WorldClient     | Connection established!
12:22:00 |  Network | WorldClient     | Authentication succeeded!
12:22:00 |  Warning | WorldClient     | C P<S | No handler for opcode SMSG_WARDEN_DATA (742) (Got unknown packet from WorldServer)
12:22:00 |  Warning | WorldSocket     | C>P S | No handler for opcode CMSG_GET_UNDELETE_CHARACTER_COOLDOWN_STATUS (14053) (Got unknown packet from ModernClient)
12:22:00 |  Warning | WorldSocket     | C>P S | No handler for opcode CMSG_BATTLE_PAY_GET_PURCHASE_LIST (14019) (Got unknown packet from ModernClient)
12:22:00 |  Warning | WorldSocket     | C>P S | No handler for opcode CMSG_BATTLE_PAY_GET_PRODUCT_LIST (14018) (Got unknown packet from ModernClient)
12:22:00 |  Warning | WorldSocket     | C>P S | No handler for opcode CMSG_UPDATE_VAS_PURCHASE_STATES (14073) (Got unknown packet from ModernClient)
12:22:00 |  Error   | AuthClient      | C P<S | Socket Closed By Server
12:22:00 |  Warning | BnetServices    | [WorldSocket][127.0.0.1:55228, Account: ACCOUNT_NAME, Game account: ACCOUNT_NAME] Client requested service ResourcesService/m:1 but this service is not implemented?

**Comment by karljohan122** [comment]
> > Warden should work fine. The server I'm playing on uses Warden. There's something wrong with your configuration. The .exe is a windows executable
> 
> TBH I have to idea - I know I am able to log to the right server but then I have errors.
> 
> Here are the full logs: 12:21:33 | Server | Server | Starting Hermes Proxy... 12:21:33 | Server | Server | Version 2023-10-19 3.10.0 dirty 12:21:33 | Server | Server | Modern (Client) Build: V1_14_2_42597 12:21:33 | Server | Server | Legacy (Server) Build: V1_12_1_5875 12:21:33 | Storage | GameData | Loading data files... 12:21:33 | Server | VersionChecker | Loaded 833 legacy opcodes. 12:21:33 | Server | VersionChecker | Loaded 1727 modern opcodes. 12:21:35 | Storage | GameData | Finished loading data. 12:21:35 | Network | Server | External IP: 127.0.0.1 12:21:35 | Server | Server | Starting BnetTcpSession service on 127.0.0.1:1119... 12:21:35 | Network | NetworkThread | Network Thread Starting 12:21:35 | Server | Server | Starting BnetRestApiSession service on 127.0.0.1:8081... 12:21:35 | Network | NetworkThread | Network Thread Starting 12:21:35 | Server | Server | Starting RealmSocket service on 127.0.0.1:8084... 12:21:35 | Network | NetworkThread | Network Thread Starting 12:21:35 | Server | Server | Starting WorldSocket service on 127.0.0.1:8086... 12:21:35 | Network | NetworkThread | Network Thread Starting 12:21:54 | Server | BnetTcpSession | Accepting connection from 127.0.0.1:53584. 12:21:55 | Network | AuthClient | C P>S | Connecting to auth server... (realmlist addr: logon.everlook.org:3724) (resolved as: 37.59.30.120:3724) 12:21:55 | Network | AuthClient | Authentication succeeded! 12:21:55 | Server | AuthClient | Requesting RealmList update for ACCOUNT_NAME 12:21:55 | Network | AuthClient | Received 3 realms. 12:21:55 | Server | RealmManager | Added realm "Everlook" at 37.59.30.120:8090 12:21:55 | Server | RealmManager | Added realm "PTR" at 37.59.30.120:8087 12:21:55 | Server | RealmManager | Added realm "Starfall" at 37.59.30.120:8099 12:21:59 | Server | WorldSocket | WorldSocket:HandleAuthSession: Client 'ACCOUNT_NAME' authenticated successfully from 127.0.0.1:55228. 12:22:00 | Network | WorldClient | Connecting to world server... 12:22:00 | Network | WorldClient | World Server address 37.59.30.120:8090 resolved as 37.59.30.120:8090 12:22:00 | Network | WorldClient | Connection established! 12:22:00 | Network | WorldClient | Authentication succeeded! 12:22:00 | Warning | WorldClient | C P<S | No handler for opcode SMSG_WARDEN_DATA (742) (Got unknown packet from WorldServer) 12:22:00 | Warning | WorldSocket | C>P S | No handler for opcode CMSG_GET_UNDELETE_CHARACTER_COOLDOWN_STATUS (14053) (Got unknown packet from ModernClient) 12:22:00 | Warning | WorldSocket | C>P S | No handler for opcode CMSG_BATTLE_PAY_GET_PURCHASE_LIST (14019) (Got unknown packet from ModernClient) 12:22:00 | Warning | WorldSocket | C>P S | No handler for opcode CMSG_BATTLE_PAY_GET_PRODUCT_LIST (14018) (Got unknown packet from ModernClient) 12:22:00 | Warning | WorldSocket | C>P S | No handler for opcode CMSG_UPDATE_VAS_PURCHASE_STATES (14073) (Got unknown packet from ModernClient) 12:22:00 | Error | AuthClient | C P<S | Socket Closed By Server 12:22:00 | Warning | BnetServices | [WorldSocket][127.0.0.1:55228, Account: ACCOUNT_NAME, Game account: ACCOUNT_NAME] Client requested service ResourcesService/m:1 but this service is not implemented?

The server I am playing on also has Warden enabled so it really shouldn't be an issue, all though we cannot be certain, since it may be that different servers have different implementations of Warden as one of the commenters previously said.

**Comment by vclst** [comment]
> i found a simple workaround by createding a tiny windows vm that only runs the proxy with the settings provided by everlook.org and just connect to it from my linux hosts that runs the wow classic client. not ideal but working :)

I forwarded the 4 ports used by HermesProxy to the VM, change the HermisProxy config to listen en 0.0.0.0 but I'm still unable to play, I'm stuck at this line: `19:01:12 |  Network | WorldClient     | World Server address 37.59.30.120:8099 resolved as 37.59.30.120:8099` ; any thoughts?
