### ISSUE TITLE
Randomize character name results in crash

### ISSUE THREAD

**Issue by henhouse** [WowLegacyCore/HermesProxy#68]
**Describe the bug**
When pressing the "Randomize" on character creation screen, the proxy crashes with the following trace:

```
22:01:44 | Error   | AuthClient | C P<S | Socket Closed By Server
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at HermesProxy.World.Server.Packets.GenerateRandomCharacterNameResult.Write() in E:\Dev\pvp\HermesProxy\HermesProxy\World\Server\Packets\CharacterPackets.cs:line 1044
   at HermesProxy.World.ServerPacket.WritePacketData() in E:\Dev\pvp\HermesProxy\HermesProxy\World\Packet.cs:line 127
   at HermesProxy.World.Server.WorldSocket.SendPacket(ServerPacket packet) in E:\Dev\pvp\HermesProxy\HermesProxy\World\Server\WorldSocket.cs:line 335
   at HermesProxy.World.Server.WorldSocket.HandleGenerateRandomCharacterNameRequest(GenerateRandomCharacterNameRequest randomCharacterName) in E:\Dev\pvp\HermesProxy\HermesProxy\World\Server\PacketHandlers\CharacterHandler.cs:line 221
   at HermesProxy.World.Server.WorldSocket.PacketHandler.<>c__DisplayClass2_0`1.<CreateDelegate>b__0(WorldSocket target, ClientPacket p) in E:\Dev\pvp\HermesProxy\HermesProxy\World\Server\WorldSocket.cs:line 1106
   at HermesProxy.World.Server.WorldSocket.PacketHandler.Invoke(WorldSocket session, WorldPacket packet) in E:\Dev\pvp\HermesProxy\HermesProxy\World\Server\WorldSocket.cs:line 1096
   at HermesProxy.World.Server.WorldSocket.HandlePacket(WorldPacket packet) in E:\Dev\pvp\HermesProxy\HermesProxy\World\Server\WorldSocket.cs:line 315
   at HermesProxy.World.Server.WorldSocket.ReadData() in E:\Dev\pvp\HermesProxy\HermesProxy\World\Server\WorldSocket.cs:line 304
   at HermesProxy.World.Server.WorldSocket.ReadHandler(SocketAsyncEventArgs args) in E:\Dev\pvp\HermesProxy\HermesProxy\World\Server\WorldSocket.cs:line 208
   at Framework.Networking.SocketBase.ProcessReadAsync(SocketAsyncEventArgs args) in E:\Dev\pvp\HermesProxy\Framework\Networking\SocketBase.cs:line 108
   at Framework.Networking.SocketBase.<.ctor>b__5_0(Object sender, SocketAsyncEventArgs args) in E:\Dev\pvp\HermesProxy\Framework\Networking\SocketBase.cs:line 53
   at System.Net.Sockets.SocketAsyncEventArgs.OnCompleted(SocketAsyncEventArgs e)
   at System.Net.Sockets.SocketAsyncEventArgs.ExecutionCallback(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pNativeOverlapped)
```

**Game Server**
vmangos

**Hermes Proxy Version**
> Version 2022-06-06 3.0.1+47(8842ac3)

**Comment by 0blu** [comment]
Will be fixed in 0025185f213f2f15734b17a09ec092d83d1f777b
#65
